services:
    app:
        image: chialab/php:8.1-apache
        container_name: laravel_10_app
        working_dir: /var/www/html
        network_mode: host
        ports:
            - "8000:80"
        volumes:
            - .:/var/www/html
        environment:
            - APACHE_DOCUMENT_ROOT=/var/www/html/public
